### contratos activos pago
POST http://167.172.127.114/sieg/public/secgeneral/estudiantes HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "draw": "1",
    "columns": [
        { "data": "foto" },
        { "data": "codigo" },
        { "data": "nombres" },
        { "data": "apellidos" },
        { "data": "programa" },
        { "data": "fecha_grado" },
        { "data": "estado_programa" },
        { "data": "estado_secretaria" },
        { "data": "acciones" }
    ],
    "order": [{ "column": 6, "dir": "desc" }],
    "start": 0,
    "length": 10,
    "search": { "value": "", "regex": false }
}

### obtener informacion adicional de estudiante
get http://167.172.127.114/sieg/public/direccion/info-adicional-estudiante/27300
Accept: application/json

### obtener documentos del estudiante
get http://167.172.127.114/sieg/public/direccion/documentos-estudiante/27300
Accept: application/json

### generar snies
POST http://167.172.127.114/sieg/public/secgeneral/generar-snies HTTP/1.1
Content-Type: application/json
Accept: application/json

{}
